image:
  file: .devcontainer/Dockerfile

tasks:
  - name: Setup Flutter
    init: flutter doctor

vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter

ports:
  - port: 8080
    onOpen: open-preview
    description: Flutter Web Preview

