name: girimote
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  cloud_firestore: ^5.0.1
  toggle_switch: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_gauges: ^26.1.35
  fl_chart: ^0.68.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/